# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BestDoggo-UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BestDoggo-UIKit
  pod 'CombineDataSources'
  pod 'Nuke'
  target 'BestDoggo-UIKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
